application: pykochr
version: landing1
runtime: python
api_version: 1

handlers:
- url: /sitemap.xml.gz
  static_files: static/sitemap.xml.gz
  upload: static/sitemap.xml.gz

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static  

- url: /.*
  script: main.py